### ISSUE TITLE
No aarch64 build

### ISSUE THREAD

**Issue by direc85** [skvark/SailKino#10]
Hi!

There doesn't seem to be an aarch64 build available, because the app isn't found on Jolla Store on Xperia 10 II. It *should* be a simple recompilation to make it happen.

If you are not actively maintaining the app anymore, or can't be bothered to install the SDK for this, I am more than happy to compile the packages and send them to you.

Thanks!

**Comment by skvark** [comment]
Yeah, if you compile the packages and send them to me I can update the app in Harbour.

**Comment by direc85** [comment]
Hi, sorry for the delay! Here are the packages. Tested with emulator, worked fine during about 5min of furious testing :grin: 

I'll create a corresponding PR shortly.

[sailkino-0.9-1.zip](https://github.com/skvark/SailKino/files/6982771/sailkino-0.9-1.zip)

**Comment by skvark** [comment]
The new version has been published in the Jolla store.

**Comment by direc85** [comment]
Confirming! The aarch64 build now shows, installs and works fine!
